name: Sync GraphQL Definitions

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-definitions-and-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Schema Repo
        uses: actions/checkout@v3
        with:
          path: "app"
          ref: master
          persist-credentials: false

      - name: Checkout GraphQL Repo
        uses: actions/checkout@v3
        with:
          path: dest
          ref: master
          repository: MoyosoreCodes/basic-graphql-service.git
          token: ${{ secrets.REPO_TOKEN }}
          persist-credentials: true

      - name: Copy definitions to graphQL service
        shell: bash
        run: |
          mkdir -p ./dest/src/typeDefs 
          mkdir -p ./dest/src/model
          cp -r app/src/typeDefs/* ./dest/src/typeDefs/
          cp -r app/src/models/* ./dest/src/model/

      - name: Commit and Push changes
        shell: bash
        working-directory: dest
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "[skip ci] Update GraphQL definitions"
          git push origin master
